version: "3.8"

services:
  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    container_name: chatbot_service
    ports:
      - "8001:8000" # Map the internal port 8000 of chatbot to external port 8001
    depends_on:
      - server
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_service
    ports:
      - "8000:8000" # Map the internal port 8000 of server to external port 8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
