name: CD Pipeline

on:
  workflow_run:
    workflows: ["Build and Push FastAPI Docker Images"]
    types: [completed]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Pull the chatbot Docker image from Docker Hub
      - name: Pull Chatbot Docker image
        run: sudo docker pull ${{secrets.DOCKER_LOGIN}}/chatbot-service:latest

      # Pull the server Docker image from Docker Hub
      - name: Pull Server Docker image
        run: sudo docker pull ${{secrets.DOCKER_LOGIN}}/server-service:latest

      # Remove any existing chatbot container if it exists
      - name: Remove old Chatbot container
        run: sudo docker rm -f chatbot-service-container || true

      # Remove any existing server container if it exists
      - name: Remove old Server container
        run: sudo docker rm -f server-service-container || true

      # Run the chatbot container (Map port 8001 on host to 8000 in container)
      - name: Run Chatbot Docker container
        run: |
          sudo docker run -d -p 8001:8000 --name chatbot-service-container ${{secrets.DOCKER_LOGIN}}/chatbot-service:latest

      # Run the server container (Map port 8002 on host to 8000 in container)
      - name: Run Server Docker container
        run: |
          sudo docker run -d -p 8000:8000 --name server-service-container ${{secrets.DOCKER_LOGIN}}/server-service:latest
